# Generated by Django 2.2 on 2022-01-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20220117_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='vote',
            field=models.BooleanField(),
        ),
    ]
