# Generated by Django 2.2 on 2022-01-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20220117_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookDetail',
        ),
    ]
