# Generated by Django 2.2 on 2022-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_post_bookdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
