# Generated by Django 3.2.11 on 2022-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_islikedstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islikedstream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
